site_name: MkDocs PoC
site_dir: ../../docs/mkdocs-output
docs_dir: ./docs
nav:
  - Details: details.md
  - Home: index.md
  - Topic Papers:
    - RWoT 5:
      - architectural-layering-for-decentralized-identification: 'rwot5/topics-and-advance-readings/Architectural-Layering-for-Decentralized-Identification'
      - biometric-credentials-as-high-privacy-verifiable-claims: 'rwot5/topics-and-advance-readings/Biometric-credentials-as-high-privacy-verifiable-claims'
      - biometric-transaction-signing-on-blockchain: 'rwot5/topics-and-advance-readings/Biometric-transaction-signing-on-blockchain'
      - blockchain-based-digital-signatures-admissibility-and-enforceability: 'rwot5/topics-and-advance-readings/Blockchain-Based-Digital-Signatures--Admissibility-and-Enforceability'
      - dif-hub-permissions-rwot-intent: 'rwot5/topics-and-advance-readings/DIF-Hub-Permissions-RWOT-Intent'
      - data-minimization-and-selective-disclosure: 'rwot5/topics-and-advance-readings/Data-minimization-and-selective-disclosure'
      - framework-for-comparison-of-identity-systems: 'rwot5/topics-and-advance-readings/Framework-for-Comparison-of-Identity-Systems'
      - identifying-challenges-in-the-digital-economy: 'rwot5/topics-and-advance-readings/Identifying-challenges-in-the-digital-economy'
      - readme: 'rwot5/topics-and-advance-readings/README'
      - rwot-user-story: 'rwot5/topics-and-advance-readings/RWOT-User-Story'
      - visa-really: 'rwot5/topics-and-advance-readings/Visa-Really'
      - activitypub-decentralized-distributed: 'rwot5/topics-and-advance-readings/activitypub-decentralized-distributed'
      - btcr-dids-ddos: 'rwot5/topics-and-advance-readings/btcr-dids-ddos'
      - byzantine-fault-tolerant-web-of-trust-based-key-value-storage: 'rwot5/topics-and-advance-readings/byzantine-fault-tolerant-web-of-trust-based-key-value-storage'
      - credential-handler-api: 'rwot5/topics-and-advance-readings/credential-handler-api'
      - did-3d-web: 'rwot5/topics-and-advance-readings/did-3d-web'
      - did-gentle-intro: 'rwot5/topics-and-advance-readings/did-gentle-intro'
      - did-primer: 'rwot5/topics-and-advance-readings/did-primer'
      - did-tooling: 'rwot5/topics-and-advance-readings/did-tooling'
      - dkms-recommendations: 'rwot5/topics-and-advance-readings/dkms-recommendations'
      - first-xdi-link-contract-between-btcr-did-and-sov-did: 'rwot5/topics-and-advance-readings/first-xdi-link-contract-between-btcr-did-and-sov-did'
      - functional-identity-primer: 'rwot5/topics-and-advance-readings/functional-identity-primer'
      - hypercerts-blockcerts-revocation: 'rwot5/topics-and-advance-readings/hypercerts-blockcerts_revocation'
      - open-badges-as-verifiable-claims: 'rwot5/topics-and-advance-readings/open-badges-as-verifiable-claims'
      - owned-vs-unowned-claims-and-ssi: 'rwot5/topics-and-advance-readings/owned-vs-unowned-claims-and-ssi'
      - paper: 'rwot5/topics-and-advance-readings/paper'
      - self-sovereign-identity-primer: 'rwot5/topics-and-advance-readings/self-sovereign-identity-primer'
      - trust-objects-proposal: 'rwot5/topics-and-advance-readings/trust-objects-proposal'
      - veres-one-did-method: 'rwot5/topics-and-advance-readings/veres-one-did-method'
      - verifiable-claims-of-impact: 'rwot5/topics-and-advance-readings/verifiable-claims-of-impact'
      - verifiable-claims-primer: 'rwot5/topics-and-advance-readings/verifiable-claims-primer'
    - RWoT 8:
       - a-did-for-every-thing-agile-driving-data-chain: 'rwot8/topics-and-advance-readings/A-DID-for-every-thing---Agile-Driving-Data-Chain'
       - aligning-ssi-with-european-union-identity-legislation-eidas: 'rwot8/topics-and-advance-readings/Aligning-SSI-with-European-Union-Identity-legislation-eIDAS'
       - anonymous-dids: 'rwot8/topics-and-advance-readings/Anonymous_DIDs'
       - applying-pola-to-user-interaction: 'rwot8/topics-and-advance-readings/Applying_POLA_to_User_Interaction'
       - did-content-references: 'rwot8/topics-and-advance-readings/DID-Content-References'
       - digital-identity-for-the-homeless: 'rwot8/topics-and-advance-readings/Digital-Identity-for-the-Homeless'
       - digitaltrustprotocol: 'rwot8/topics-and-advance-readings/DigitalTrustProtocol'
       - p2p-did: 'rwot8/topics-and-advance-readings/P2P-DID'
       - proof-of-key-ownership-with-openid-connect-self-issued-identities: 'rwot8/topics-and-advance-readings/Proof_of_Key_Ownership_with_OpenID_Connect_Self-Issued_Identities'
       - providing-decentralized-identity-to-the-most-vulnerable-populations: 'rwot8/topics-and-advance-readings/Providing_Decentralized_Identity_to_the_most_vulnerable_populations'
       - rwot-local-chapters: 'rwot8/topics-and-advance-readings/RWOT-local-chapters'
       - ssi-frameworkproposal: 'rwot8/topics-and-advance-readings/SSI-FrameworkProposal'
       - ssi-frameworkproposal: 'rwot8/topics-and-advance-readings/SSI-FrameworkProposal'
       - the-untimely-death-of-ssi: 'rwot8/topics-and-advance-readings/The-Untimely-Death-Of-SSI'
       - universal-did-operations: 'rwot8/topics-and-advance-readings/Universal-DID-Operations'
       - using-immutable-data-objects: 'rwot8/topics-and-advance-readings/Using-Immutable-Data-Objects'
       - zero-knowledge-proofs: 'rwot8/topics-and-advance-readings/Zero-knowledge-Proofs'
       - bootstrap-web-of-trust-reliance-lifecycle: 'rwot8/topics-and-advance-readings/bootstrap_web-of-trust_reliance-lifecycle'
       - bringing-dependencies-btcr-wallet-to-swift-ecosystem: 'rwot8/topics-and-advance-readings/bringing-dependencies-btcr-wallet-to-swift-ecosystem'
       - contextual-nondiscrete-identity: 'rwot8/topics-and-advance-readings/contextual_nondiscrete_identity'
       - credentials-and-correlation: 'rwot8/topics-and-advance-readings/credentials-and-correlation'
       - data-vala-realization: 'rwot8/topics-and-advance-readings/data-vala-realization'
       - decentralized-digital-identity-book: 'rwot8/topics-and-advance-readings/decentralized-digital-identity-book'
       - did-fee-market-using-micropayments: 'rwot8/topics-and-advance-readings/did-fee-market-using-micropayments'
       - did-namespace-records: 'rwot8/topics-and-advance-readings/did-namespace-records'
       - did-primer-extended: 'rwot8/topics-and-advance-readings/did-primer-extended'
       - did-primer: 'rwot8/topics-and-advance-readings/did-primer'
       - did-spec-current-status: 'rwot8/topics-and-advance-readings/did-spec-current-status'
       - did-ux: 'rwot8/topics-and-advance-readings/did-ux'
       - digital-contraception: 'rwot8/topics-and-advance-readings/digital-contraception'
       - diverse-teams: 'rwot8/topics-and-advance-readings/diverse-teams'
       - educational-credentialing-ecosystem: 'rwot8/topics-and-advance-readings/educational-credentialing-ecosystem'
       - exploring-adoption-of-sharing-vcs: 'rwot8/topics-and-advance-readings/exploring_adoption_of_sharing_vcs'
       - financing-self-sovereign-stack: 'rwot8/topics-and-advance-readings/financing-self-sovereign-stack'
       - functional-identity-primer: 'rwot8/topics-and-advance-readings/functional-identity-primer'
       - glossary-primer: 'rwot8/topics-and-advance-readings/glossary-primer'
       - graphs-everywhere: 'rwot8/topics-and-advance-readings/graphs-everywhere'
       - handshake: 'rwot8/topics-and-advance-readings/handshake'
       - humanity-api: 'rwot8/topics-and-advance-readings/humanity-API'
       - identity-containers: 'rwot8/topics-and-advance-readings/identity-containers'
       - identity-for-people-places: 'rwot8/topics-and-advance-readings/identity-for-people-places'
       - idm-concept: 'rwot8/topics-and-advance-readings/idm-concept'
       - idm-spec: 'rwot8/topics-and-advance-readings/idm-spec'
       - implementing-threshold-schemes: 'rwot8/topics-and-advance-readings/implementing-threshold-schemes'
       - introductory-capability-dht-concept: 'rwot8/topics-and-advance-readings/introductory-capability-dht-concept'
       - journalistic-use-cases: 'rwot8/topics-and-advance-readings/journalistic-use-cases'
       - libp2p-did-auth: 'rwot8/topics-and-advance-readings/libp2p_did_auth.'
       - multiformat-superfriends: 'rwot8/topics-and-advance-readings/multiformat-superfriends'
       - name-services-and-ssi: 'rwot8/topics-and-advance-readings/name-services-and-ssi'
       - notebook-workbench: 'rwot8/topics-and-advance-readings/notebook-workbench'
       - oidc-profile-for-ssi: 'rwot8/topics-and-advance-readings/oidc-profile-for-ssi'
       - on-interpersonal-data: 'rwot8/topics-and-advance-readings/on-interpersonal-data'
       - psdad: 'rwot8/topics-and-advance-readings/psdad'
       - rightsframeworks: 'rwot8/topics-and-advance-readings/rightsframeworks'
       - security-shamirs: 'rwot8/topics-and-advance-readings/security_shamirs'
       - social-key-recovery: 'rwot8/topics-and-advance-readings/social-key-recovery'
       - ssi20xx-model-use-case-def: 'rwot8/topics-and-advance-readings/ssi20XX-model-use-case-def'
       - supporting-btcr: 'rwot8/topics-and-advance-readings/supporting-btcr'
       - the-untimely-death-of-ssi: 'rwot8/topics-and-advance-readings/the-untimely-death-of-ssi'
       - trusting-attributes: 'rwot8/topics-and-advance-readings/trusting-attributes'
       - united-humans-critiqal-questions: 'rwot8/topics-and-advance-readings/united-humans-critiqal-questions'
       - universal-id-framework: 'rwot8/topics-and-advance-readings/universal-id-framework'
       - universal-ledger-agent: 'rwot8/topics-and-advance-readings/universal-ledger-agent'
       - universe-is-blockchain: 'rwot8/topics-and-advance-readings/universe-is-blockchain'
       - vcs-agent-centric: 'rwot8/topics-and-advance-readings/vcs-agent-centric'
       - verifiable-credentials-primer: 'rwot8/topics-and-advance-readings/verifiable-credentials-primer'
       - verifiable-displays-in-html: 'rwot8/topics-and-advance-readings/verifiable-displays-in-HTML'
       - verifiable-postal-address-claims: 'rwot8/topics-and-advance-readings/verifiable-postal-address-claims'
       - w3c-identity-workshop-report: 'rwot8/topics-and-advance-readings/w3c-identity-workshop-report'
       - why-wots-work: 'rwot8/topics-and-advance-readings/why-WOTs-work'
